/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Endianness {
  Big = 0,
  Little = 1
}
export class BinaryStream {
  /**
  * The binary data of the stream.
  */
  binary: Array<number>
  /**
  * The current offset of the stream.
  */
  offset: number
  /**
  * Creates a new BinaryStream with an optional JavaScript Buffer.
  */
  constructor(buffer?: Buffer | undefined | null, offset?: number | undefined | null)
  /**
  * Creates a new BinaryStream from a binary vector.
  */
  static from(binary: Array<number>, offset?: number | undefined | null): BinaryStream
  /**
  * Creates a new BinaryStream from a JavaScript Buffer.
  */
  static fromBuffer(buffer: Buffer, offset?: number | undefined | null): BinaryStream
  /**
  * Reads a number of bytes from the stream.
  */
  read(length: number): Array<number>
  /**
  * Reads a number of bytes from the stream and returns a JavaScript Buffer.
  */
  readBuffer(length: number): Buffer
  /**
  * Writes a number of bytes to the stream.
  */
  write(data: Array<number>): void
  /**
  * Writes a JavaScript Buffer to the stream.
  */
  writeBuffer(data: Buffer): void
  /**
  * Reads the remaining bytes from the stream.
  */
  readRemaining(): Array<number>
  /**
  * Reads the remaining bytes from the stream and returns a JavaScript Buffer.
  */
  readRemainingBuffer(): Buffer
  /**
  * Skips a number of bytes from the stream.
  */
  skip(length: number): number
  /**
  * Checks if the cursor is at the end of the stream.
  */
  cursorAtEnd(): boolean
  /**
  * Checks if the cursor is at the start of the stream.
  */
  cursorAtStart(): boolean
  /**
  * Gets the binary as a JavaScript Buffer.
  */
  getBuffer(): Buffer
  /**
  * Reads a string from the stream.
  */
  readString(): string
  /**
  * Writes a string to the stream.
  */
  writeString(data: string): void
  readBigString(): string
  writeBigString(data: string): void
  readLittleString(): string
  writeLittleString(data: string): void
  readUuid(): string
  writeUuid(data: string): void
  /**
  * Reads a boolean from the stream.
  */
  readBool(): boolean
  /**
  * Writes a boolean to the stream.
  */
  writeBool(data: boolean): void
  /**
  * Reads an unsigned 8-bit ( 1 byte ) integer to the stream. ( 0 to 255 )
  */
  readByte(): number
  /**
  * Writes an unsigned 8-bit ( 1 byte ) integer to the stream. ( 0 to 255 )
  */
  writeByte(data: number): void
  /**
  * Reads an unsigned 8-bit ( 1 byte ) integer to the stream. ( 0 to 255 )
  */
  readUint8(): number
  /**
  * Writes an unsigned 8-bit ( 1 byte ) integer to the stream. ( 0 to 255 )
  */
  writeUint8(data: number): void
  /**
  * Reads a signed 8-bit ( 1 byte ) integer to the stream. ( -128 to 127 )
  */
  readInt8(): number
  /**
  * Writes a signed 8-bit ( 1 byte ) integer to the stream. ( -128 to 127 )
  */
  writeInt8(data: number): void
  /**
  * Reads an unsigned 16-bit ( 2 bytes ) integer to the stream. ( 0 to 65535 )
  */
  readUint16(endian?: Endianness | undefined | null): number
  /**
  * Writes an unsigned 16-bit ( 2 bytes ) integer to the stream. ( 0 to 65535 )
  */
  writeUint16(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 16-bit ( 2 bytes ) integer to the stream. ( -32768 to 32767 )
  */
  readInt16(endian?: Endianness | undefined | null): number
  /**
  * Writes a signed 16-bit ( 2 bytes ) integer to the stream. ( -32768 to 32767 )
  */
  writeInt16(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads an unsigned 16-bit ( 2 bytes ) integer to the stream. ( 0 to 65535 )
  */
  readUShort(endian?: Endianness | undefined | null): number
  /**
  * Writes an unsigned 16-bit ( 2 bytes ) integer to the stream. ( 0 to 65535 )
  */
  writeUShort(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 16-bit ( 2 bytes ) integer to the stream. ( -32768 to 32767 )
  */
  readShort(endian?: Endianness | undefined | null): number
  /**
  * Writes a signed 16-bit ( 2 bytes ) integer to the stream. ( -32768 to 32767 )
  */
  writeShort(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads an unsigned 24-bit ( 3 bytes ) integer to the stream. ( 0 to 16777215 )
  */
  readUint24(endian?: Endianness | undefined | null): number
  /**
  * Writes an unsigned 24-bit ( 3 bytes ) integer to the stream. ( 0 to 16777215 )
  */
  writeUint24(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 24-bit ( 3 bytes ) integer to the stream. ( -8388608 to 8388607 )
  */
  readInt24(endian?: Endianness | undefined | null): number
  /**
  * Writes a signed 24-bit ( 3 bytes ) integer to the stream. ( -8388608 to 8388607 )
  */
  writeInt24(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads an unsigned 32-bit ( 4 bytes ) integer to the stream. ( 0 to 4294967295 )
  */
  readUint32(endian?: Endianness | undefined | null): number
  /**
  * Writes an unsigned 32-bit ( 4 bytes ) integer to the stream. ( 0 to 4294967295 )
  */
  writeUint32(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 32-bit ( 4 bytes ) integer to the stream. ( -2147483648 to 2147483647 )
  */
  readInt32(endian?: Endianness | undefined | null): number
  /**
  * Writes a signed 32-bit ( 4 bytes ) integer to the stream. ( -2147483648 to 2147483647 )
  */
  writeInt32(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads an unsigned 64-bit ( 8 bytes ) integer to the stream. ( 0 to 18446744073709551615 )
  */
  readUint64(endian?: Endianness | undefined | null): bigint
  /**
  * Writes an unsigned 64-bit ( 8 bytes ) integer to the stream. ( 0 to 18446744073709551615 )
  */
  writeUint64(data: bigint, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 64-bit ( 8 bytes ) integer to the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  readInt64(endian?: Endianness | undefined | null): bigint
  /**
  * Writes a signed 64-bit ( 8 bytes ) integer to the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  writeInt64(data: bigint, endian?: Endianness | undefined | null): void
  readFloat32(endian?: Endianness | undefined | null): number
  writeFloat32(data: number, endian?: Endianness | undefined | null): void
  /**
  * Reads an unsigned 64-bit ( 8 bytes ) integer to the stream. ( 0 to 18446744073709551615 )
  */
  readULong(endian?: Endianness | undefined | null): bigint
  /**
  * Writes an unsigned 64-bit ( 8 bytes ) integer to the stream. ( 0 to 18446744073709551615 )
  */
  writeULong(data: bigint, endian?: Endianness | undefined | null): void
  /**
  * Reads a signed 64-bit ( 8 bytes ) integer to the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  readLong(endian?: Endianness | undefined | null): bigint
  /**
  * Writes a signed 64-bit ( 8 bytes ) integer to the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  writeLong(data: bigint, endian?: Endianness | undefined | null): void
  /**
  * Reads a 32 bit ( 4 bytes ) unsigned variable length integer from the stream. ( 0 to 4294967295 )
  */
  readVarInt(): number
  /**
  * Writes a 32 bit ( 4 bytes ) unsigned variable length integer to the stream. ( 0 to 4294967295 )
  */
  writeVarInt(data: number): void
  /**
  * Reads a 32 bit ( 4 bytes ) zigzag encoded signed variable length integer from the stream. ( -2147483648 to 2147483647 )
  */
  readZigZag(): number
  /**
  * Writes a 32 bit ( 4 bytes ) zigzag encoded signed variable length integer to the stream. ( -2147483648 to 2147483647 )
  */
  writeZigZag(data: number): void
  /**
  * Reads a 64 bit ( 8 bytes ) unsigned variable length integer from the stream. ( 0 to 18446744073709551615 )
  */
  readVarLong(): bigint
  /**
  * Writes a 64 bit ( 8 bytes ) unsigned variable length integer to the stream. ( 0 to 18446744073709551615 )
  */
  writeVarLong(data: bigint): void
  /**
  * Reads a 64 bit ( 8 bytes ) zigzag encoded signed variable length integer from the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  readZigZong(): bigint
  /**
  * Writes a 64 bit ( 8 bytes ) zigzag encoded signed variable length integer to the stream. ( -9223372036854775808 to 9223372036854775807 )
  */
  writeZigZong(data: bigint): void
}
